const router = require('express').Router()
const AdminRouter = require('./AdminRouter')
const StudentRouter = require('./StudentRouter')
const TeacherRouter = require('./TeacherRouter')
const ExamRouter = require('./ExamRouter')
const QuestionBankRouter = require('./QuestionBankRouter')
const ClassRoomRouter = require('./ClassroomRouter')
const SubjectRouter = require('./SubjectRouter')
const { Login } = require('../controllers')

router.use('/admin', AdminRouter)
router.post('/login', Login)
router.use('/students', StudentRouter)
router.use('/teachers', TeacherRouter)
router.use('/exams', ExamRouter)
router.use('/questions', QuestionBankRouter)
router.use('/classrooms', ClassRoomRouter)
router.use('/subjects', SubjectRouter)

module.exports = router